language: python
python:
- '3.5'
install:
  - pip install -r requirements.txt
sudo: required
services:
  - docker
script:
  - ./scripts/docker_login.sh && ./scripts/docker_build.sh
  - ./scripts/docker_run.sh
  - python3 -m leveldbs.test.zmq_client && ./scripts/docker_push.sh
deploy:
  provider: pypi
  user: infinityfuture
  password:
    secure: yaWdBjOkCnLk/b7LCmBjAHJPEAl0lcioTov5esSnOL6JGZHCcDJ4nyKj9jRsZYkoBLZ4kvFrfbmiSAptAa1xAKrzpgM6zh5/E+GEFVU2HYc+vSjKs4036YxMOgBJxKgG0hN3oECFJOV62CAthaql03aiYDUuooHGKFoEFNL6TVzkzKBGSV7mDN9sbuU70a9SkR3AIOGFY6pz1dqUroQQaPaF6d8W+cqlR3I2/5B3448DcyYPkkcvEaRZULVQ7nuq7WCGw5PboC2iOKh8Xe6nhcrTI/RtPG9Pked0UMRMaLe8TxMsDZ05FeRHiA9pk3yjO70dXzsFXhZdxD6QmnEuTFhlEAu1mMxxqKaOIciQebx+DHMw4e6Wzf7fuvPVwfU2YA0314jwjyFrdQrJvP0qgT0b6S0E6efwFWgOrV+nfdIrUoOG29o8AS3bY2SbfeajfJ9ExqNc9Z4nmRGWLC0aIgf/m9qyGH6XLdXZ3/Lcxja15J2OBRdDxCv2dcWZEiyGuzE3lNQ3615n15C80zzL4sN6H26N9NZ9mbDdhEEvnFTDNcXiqgpNIXewJkYbEcrQsAC3NZF6R9YgQ/obZc7DSWLL3Lc8tb4PdyQdBZ2IRhfBKhb0rqhrSoBUKEukLohhkk1wrdJKPaEITVbC0niBERYdAgdVoRqtL+4giJoEyV4=